### ISSUE TITLE
Add Changeset Comment

### ISSUE THREAD

**Issue by Nakaner** [osmlab/latest-changes#2]
Could you please add the changeset comment at every listed changeset below user name, date and Achavi link? WhoDidIt does this and latest-changes could replace most of WhoDidIt's use cases if it would output the changeset comment, too.

**Comment by tyrasd** [comment]
Isn't the changeset comment displayed quite prominently in the list already?

**Comment by Nakaner** [comment]
Maybe you alreday have changed this.
